global:
  storageClass: longhorn
auth:
  rootPassword: root@mysql
primary:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
metrics:
  enabled: true
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
