ingress:
  enabled: true
  className: nginx
  hosts:
    - host: cloudreve.panghuli.tech
      paths:
        - path: /
          pathType: Prefix
persistence:
  enabled: true
  storageClassName: longhorn
  size: 10Gi
conf.ini:
  System:
    SessionSecret: admin@cloudreve
  Database:
    # 数据库类型，目前支持 sqlite/mysql/mysql/postgres
    Type: mysql
    Port: 3306
    User: cloudreve
    Password: cloudreve@MySQL2023
    Host: mysql
    Name: cloudreve
    Charset: utf8mb4
    # 进程退出前安全关闭数据库连接的缓冲时间
    GracePeriod: 30
    # 使用 Unix Socket 连接到数据库
    UnixSocket: false
  Redis:
    Server: redis-master.home-lab.svc.cluster.local:6379
    Password: root@redis
    DB: 0
